version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.71.0/24

volumes: 
  workspace: 
  
services:
  control:
    image: codespaces/theia:v2.0.0
    ports:
      - "8001:8000"
    volumes:
      - workspace:/workspace
    networks:
      custom:
        ipv4_address: 192.168.71.10
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: control
    restart: always
  lb:
    image: codespaces/ansible-node:centos7
    ports:
       - "90:80"
    networks:
      custom:
        ipv4_address: 192.168.71.11
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: lb
    restart: always
    privileged: true
  app1:
    image: codespaces/ansible-node:centos7
    ports:
       - "91:80"
    networks:
      custom:
        ipv4_address: 192.168.71.12
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: app1
    restart: always
    privileged: true
  app2:
    image: codespaces/ansible-node:centos7
    ports:
      - "92:80"
    networks:
      custom:
        ipv4_address: 192.168.71.13
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: app2
    restart: always
    privileged: true
  app3:
    image: codespaces/ansible-node:ubuntu1804
    ports:
      - "93:80"
    networks:
      custom:
        ipv4_address: 192.168.71.15
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: app3
    restart: always
    privileged: true
  db:
    image: codespaces/ansible-node:centos7
    ports:
      - "3306:3306"
    networks:
      custom:
        ipv4_address: 192.168.71.14
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: db
    restart: always
    privileged: true
